**Welcome to Numpy Tutorial**

In [1]:
import numpy as np

**Array creation: conversion from other python structures**

In [2]:
myarr=np.array([[1,2,3,422]],np.int64)
myarr

array([[  1,   2,   3, 422]], dtype=int64)

In [3]:
myarr[0,1]

2

In [4]:
myarr.shape

(1, 4)

In [5]:
myarr.ndim

2

In [6]:
myarr.dtype

dtype('int64')

In [7]:
myarr.size

4

In [8]:
myarr[0,1]=44
myarr

array([[  1,  44,   3, 422]], dtype=int64)

In [9]:
mult=np.array([[1,2,3],[4,5,6],[7,8,9]])
mult

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
print(mult.dtype)
print(mult.shape)
print(mult.size)
print(mult.ndim)

int32
(3, 3)
9
2


**Array creation: intrinsic numpy array creation objects**

In [11]:
arr=np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [12]:
arr2=np.arange(15)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
lspace=np.linspace(1,2,6)
lspace

array([1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [14]:
z=np.zeros((4,3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
z=np.ones((4,4))
z

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
emp=np.empty((4,1))
emp

array([[0.00000000e+000],
       [1.13530579e-311],
       [1.13632468e-311],
       [1.13632501e-311]])

In [17]:
like=np.empty_like(arr)
like

array([1864394083, 1867522150, 1931508076, 1701409381, 1868767347])

In [18]:
ide=np.identity(7)
ide

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [19]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
a.shape

(10,)

In [21]:
a.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [22]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
a=a.reshape(5,2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [24]:
arr.ravel()

array([0, 1, 2, 3, 4])

In [25]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
x.sum()

45

In [27]:
x.sum(axis=0)

array([12, 15, 18])

In [28]:
x.sum(axis=1)

array([ 6, 15, 24])

In [29]:
y=np.array([[[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]],[[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]],[[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]],[[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]]])
y.reshape(9,12)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3],
       [4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6],
       [7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3],
       [4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6],
       [7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3],
       [4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6],
       [7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [30]:
y.shape

(4, 3, 3, 3)

In [31]:
x.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [32]:
y.ndim

4

In [33]:
x.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [34]:
l=np.array([1,3,2,4])
l

array([1, 3, 2, 4])

In [35]:
l.sum(axis=0)

10

In [36]:
l.flat

In [37]:
l.nbytes

16

In [38]:
l.argmax()

3

In [39]:
l.argmin()

0

In [40]:
l.sort()
l

array([1, 2, 3, 4])

In [41]:
np.where(x>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [42]:
py_ar=[0,2,56,78]

In [43]:
np_ar=np.array(py_ar)

In [44]:
import sys
sys.getsizeof(1)*len(py_ar)

112

In [45]:
sys.getsizeof(1)*len(np_ar)

112

In [46]:
sys.getsizeof(np_ar)

128

In [47]:
sys.getsizeof(py_ar)

88

In [48]:
np_ar.itemsize*np_ar.size

16

In [49]:
#Tejas' Python Code